### ISSUE TITLE
Changing Jetty settings through SparkJava

### ISSUE THREAD

**Issue by QMG-kazala** [perwendel/spark#314] opened 2015-08-03 12:56 UTC
I'm using SparkJava 2.2 which is using Jetty 9.0.2.

I'm getting "Form too large" exception which is thrown by Jetty. I know how to solve this problem if I was using Jetty directly:

http://www.eclipse.org/jetty/documentation/current/setting-form-size.html

I've already checked that setting env.properties has no effect.
Debugger doesn't even stop at any breakpoint set within org.eclipse.jetty.server.handlerContextHandler... Plus when it stops at org.eclipse.jetty.server.Request breakpoints, _context property is null.

Is there any way to create context for Jetty requests? Is there any way to alter maxFormContentSize?

**Comment by keltik85** [comment] 2015-09-24 08:47
Same problem here.

**Comment by QMG-kazala** [comment] 2015-09-24 12:58
keltik85 , it doesn't seem like it's gonna change. I would use sth else instead of Spark if I were you.

**Comment by keltik85** [comment] 2015-09-25 08:06
I am sending a picture as a byte-array-string inside my request-params to the SparkServer and therefore the Post becomes too big. (3.5MB picture produces POST-request of approx. 7MB (2MB is the "hardcoded-jetty-maximum-post-size"))

**Comment by koraytaylan** [comment] 2016-01-05 13:52
I was quite happy with spark until discovering that it is not possible to configure embedded jetty server :cry:

**Comment by QMG-kazala** [comment] 2016-01-05 14:25
Same here koraytaylan. I've switched to Dropwizard..... Bye Bye SparkJava :(

**Comment by tinustate** [comment] 2016-01-23 12:15
+1 i was researching a lightweight way of creating a tiny web gui backed up by java (need to use rmi) and stumbled across sparkjava which really looked quite nice. But not able to solve jetty problems is a bit of a problem. But i might look at sparkjava again on future projects for sure and see how it evolves, it is very hard to create a project that does everything right the first time.

**Comment by Melody12ab** [comment] 2016-02-29 11:01
same problem，expect owner solve the problem

**Comment by tom-smalls** [comment] 2016-03-14 17:12
@perwendel are there any plans to expose parts of the embedded Jetty server? For me, I would like to be able to inject my own SocketConnectorFactory as I would like to enable http/2. This seems achievable is pass in via the ignite call from SparkInstance before any routes have been set up.

**Comment by Maunte** [comment] 2016-05-05 18:51
+1 for this.

**Comment by ylemoigne** [comment] 2016-05-08 01:30
Well I used a workaround... It's as ugly at it seems...
Copy the EmbeddedJettyServer, JettyFactory and JettyServer classes in your project.
In the copied JettyFactory change the `new` to you copied EmbeddedJettyServer.

Now, here my main initialization (in kotlin, sorry):
```
  val niceMap = HashMap<Any, EmbeddedServerFactory>()
  niceMap.put(EmbeddedServers.defaultIdentifier(), CustomJettyFactory())

  val evilsMap = object: HashMap<Any, EmbeddedServerFactory>(niceMap){
    override fun put(key: Any, value: EmbeddedServerFactory): EmbeddedServerFactory?  = value
  }

  val factoriesField = EmbeddedServers::class.java.getDeclaredField("factories")
  factoriesField.isAccessible = true
  factoriesField.set(null, evilsMap)
```

Roughly translated in java :
```
  Map<Object, EmbeddedServerFactory> niceMap = new HashMap<>();
  niceMap.put(EmbeddedServers.defaultIdentifier(), new CustomJettyFactory());

  Map<Object, EmbeddedServerFactory> evilsMap = new HashMap<Object, EmbeddedServerFactory>(niceMap){
    public EmbeddedServerFactory put(Object key, EmbeddedServerFactory value) {return value;}
  };

  Field factoriesField = EmbeddedServers.class.getDeclaredField("factories")
  factoriesField.setAccessible(true)
  factoriesField.set(null, evilsMap)
```

**Comment by 1inuxoid** [comment] 2016-05-12 10:58
I am up-voting this issue as it seems to be really one of the very few missing bits for broader application of Spark.

**Comment by kshep92** [comment] 2016-05-15 05:12
Upvoted. We definitely need a nice, clean way of changing some of the basic Jetty settings. I'll look into this as well during the week.

**Comment by thienan** [comment] 2016-05-17 03:29
Upvoted. I want to change the jetty session management to mongodb

**Comment by ruurd** [comment] 2016-05-17 12:34
If I look in the code it should be possible to run spark as a servlet in a different container... implying that you yourself can configure it to suit. That said, posting a picture in a form or posting very large forms can open the door to other problems. Security is one of the reasons to keep the size of a POST in check and making it < 2M...

**Comment by kshep92** [comment] 2016-05-17 12:44
I think the size of uploads allowed should ultimately be determined by the developer of the application and not a restriction imposed by the framework.

**Comment by ruurd** [comment] 2016-05-17 13:16
You're lucky you're not using PHP where the default was 128K. I think a reasonable default is useful especially since developers and especially the less experienced ones are probably going to forget to configure that. Or misconfigure it. Can I remind you about that time Exchange was configured as an open relay as a default?

**Comment by danechitoaie** [comment] 2016-05-17 14:31
Having a default totally makes sense, but you should still be able to configure the settings yourself if you need to.

**Comment by ruurd** [comment] 2016-05-17 16:02
Well in this case I think that you then must run spark in a different container as I indicated.

**Comment by serge-nikitin** [comment] 2016-06-20 11:42
Is it possible to fix this problem?

**Comment by QMG-kazala** [comment] 2016-06-20 11:48
Use Dropwizard ;)
That's actually not a joke. That's what we did.

**Comment by danechitoaie** [comment] 2016-06-20 12:28
> Dropwizard is a Java framework for developing ops-friendly, high-performance, RESTful web services.

What if I don't need to develop a "RESTfull webservice"? What if I need to develop a normal web app?

**Comment by QMG-kazala** [comment] 2016-06-20 13:08
I do understand the problem. Dropwizard is not for everybody. I don't like this solution either, but it worked for us. You have to make your own decision. Other solutions?

You could get the jetty source from git and change maxFormContentSize,maxFormKey in the Rquest.java. Except... you would have to do it each time you wanted to use a new version of Spark. Bleh!

You could look for other similar solutions..... 
You could contact Jetty authors, discuss the problem with them, introduce changes in your branch, create a pull request.... and wait for them to accept it.
You could... pay them to do it for you ;)
What can I say. There is no perfect solution.

**Comment by tipsy** [comment] 2016-06-20 13:10
How can I reproduce this? I can upload images much larger than this by setting the form to multipart.

**Comment by QMG-kazala** [comment] 2016-06-20 13:44
eg. create a form with an input text and paste in very long text.

**Comment by serge-nikitin** [comment] 2016-06-20 13:54
I just tried https://github.com/decebals/pippo framework and it's possible to update  maxFormContentSize with system property:

`System.setProperty("org.eclipse.jetty.server.Request.maxFormContentSize", "5000000");`

**Comment by swellard** [comment] 2016-06-21 14:15
I would really like to be able to set a context path to allow different services on the same port. Jetty exposes this but it doesn't seem possible to get to that setting in the Spark embedded Jetty. This seems like an oversight. Had considered a configuration value to put in the front of every route but this feels 'wrong' when with Jetty you can easily set a context path. Can this be addressed?

**Comment by toyg** [comment] 2016-08-10 12:40
Allowing Jetty customizations would also enable goodies like access to SSL client certificates and other advanced SSL details with zero effort.

**Comment by tinustate** [comment] 2016-10-11 14:52
A new project, a new look at spark.
I'm surprised to see that this issue hasn't been solved.
Isn't it possible to implement something similar like spring-boot does:
http://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/context/embedded/jetty/JettyServerCustomizer.html
This gives you full control of the jetty Server object.

**Comment by Maunte** [comment] 2016-10-11 15:13
It seems like the project has become quite stagnant.  I've been working on migrating to DropWizard.

**Comment by koraytaylan** [comment] 2016-10-11 15:26
@Maunte I am also considering whether I should live with shortcomings or switch to spring-boot or dropwizard so can you tell me what makes DropWizard a better replacement for you other than this particular issue?

**Comment by vemacs** [comment] 2016-10-11 15:53
Also take a look at pippo: https://github.com/decebals/pippo

The API is very similar but it's more modular and does support more configuration (setMaximumUploadSize, you also easily override the ServletContextHandler)

**Comment by kshep92** [comment] 2016-10-11 15:58
My fears with this framework have been realised. I've been using Jooby for the last few months and I'm really happy with it https://github.com/jooby-project/jooby

**Comment by perwendel** [comment] 2016-10-11 17:35
We will look at this when there is time. We are currently two persons working with Spark on our _sparetime_ besides our dayjobs and our private lifes with all the time that goes into that. This seems to be a wanted functionality, hence we will prioritize this higher. However, one can't expect that everything everyone wants will be fixed in one day, or week or even in the next release. We are doing what we can. And for the record, this is not a forum for promoting other frameworks, it's for filing and discussing issues/feature requests etc for Spark.

**Comment by maxxyme** [comment] 2016-10-12 07:49
I totally get it (few people maintaining, spare time, etc.)
But people are stuck with unresolved issues. So either they fix it by themselves - which they can because the code is open sourced (thank whoever you wanna thank), or they switch to something else which does not have this kind of issue, promptly advised by some fellow participants here.

**Comment by toyg** [comment] 2016-10-20 13:33
@perwendel ignore the ungrateful assholes, that's just the internet being the internet. 

Exposing Jetty as much as possible would likely take some pressure off you, since things like SSL would stop being your problem, leaving you free to concentrate on the declaration/routing thing that spark does so well.

Thanks for all the great work!

**Comment by perwendel** [comment] 2016-11-03 11:08
I will start look at this now. If there are any proposals on how to do this the best way I'm all ears!

**Comment by maxxyme** [comment] 2016-11-03 15:56
You've already got this proposal: https://github.com/perwendel/spark/issues/314#issuecomment-252940974 ;)

**Comment by streamflex** [comment] 2016-11-07 13:08
@perwendel thanks for your great work on this project. I love Spark for being small and clean. Having just started a new project with Spark, the prospect of convenient Jetty configuration is very welcome.

**Comment by boatmeme** [comment] 2017-01-05 17:13
+1

**Comment by perwendel** [comment] 2017-04-08 16:26
Merged PR #813 opens up possibility for any Jetty setting in Spark embedded.

**Closed by perwendel** 2017-04-08 16:26 UTC
Labels: Feature request, Much wanted

**Comment by QMG-kazala** [comment] 2017-04-10 09:13
Awesome!!!!
BIG THX to everyone involved! :)
Cheers

**Comment by ijabz** [comment] 2018-03-07 21:31
So its fixed in 2.6 but how do I use it ? 
Some explanation on how we can now configure to avoid "Form too large" exception' would be much appreciated.

**Comment by kliakos** [comment] 2019-02-06 20:38
Any example how the Jetty server is full configurable now?

**Comment by tweenietomatoes** [comment] 2019-02-06 21:11
> 
> 
> Any example how the Jetty server is full configurable now?

using 2.2 with 9.0.2 ?

**Comment by kliakos** [comment] 2019-02-06 21:26
> > Any example how the Jetty server is full configurable now?
> 
> using 2.2 with 9.0.2 ?

I am on Sprarkjava 2.7.2.

I actually found out how to set a max queued request limit that I wanted. I don't see however how to completely configure a Jetty server and have access to all attributes.

```java
EmbeddedServers.add(EmbeddedServers.Identifiers.JETTY, new EmbeddedJettyFactory().withThreadPool(
    new QueuedThreadPool(200, 8, 60000, new BlockingArrayQueue<>(8, 8, 100))
));

**Comment by tweenietomatoes** [comment] 2019-02-06 21:35
> 
> 
> > > Any example how the Jetty server is full configurable now?
> > 
> > 
> > using 2.2 with 9.0.2 ?
> 
> I am on Sprarkjava 2.7.2.
> 
> I actually found out how to set a max queued request limit that I wanted. I don't see however how to completely configure a Jetty server and have access to all attributes.
> 
> ```java
> EmbeddedServers.add(EmbeddedServers.Identifiers.JETTY, new EmbeddedJettyFactory().withThreadPool(
>     new QueuedThreadPool(200, 8, 60000, new BlockingArrayQueue<>(8, 8, 100))
> ));
> ```

This section had threads, ssl etc.
http://sparkjava.com/documentation#embedded-web-server

For further you need XML config.
https://www.eclipse.org/jetty/documentation/9.4.x/quick-start-configure.html#quickstart-config-how

**Comment by toyg** [comment] 2019-02-11 18:57
I've tried to put together an howto as simple as I could manage, explaining step by step: http://blog.pythonaro.com/2019/02/how-to-customise-jetty-embedded-in.html
