### ISSUE TITLE
Websocket HowTo seems to be outdated...

### ISSUE THREAD

**Issue by neilyoung** [perwendel/spark#957] opened 2017-12-19 20:05 UTC
Well... sort of.

I'm referring to the Websocket part here: 

http://sparkjava.com/documentation#websockets

The strange thing: Everything works as expected, if I create a JAR containing this snippet.

But once I obfuscate it using proguard I'm getting this at runtime:

```
Exception in thread "main" java.lang.IllegalArgumentException: WebSocket handler must implement 'WebSocketListener' or be annotated as '@WebSocket'
	at spark.embeddedserver.jetty.websocket.WebSocketHandlerWrapper.validateHandlerClass(WebSocketHandlerWrapper.java:22)
	at spark.embeddedserver.jetty.websocket.WebSocketHandlerClassWrapper.<init>(WebSocketHandlerClassWrapper.java:11)
	at spark.Service.webSocket(Service.java:301)
	at spark.Spark.webSocket(Spark.java:1138)
	at com.myCompany.myProject.f.<init>(Unknown Source)
	at com.myCompany.myProject.MainApp.<init>(Unknown Source)
	at com.myCompany.myProject.MainApp.main(Unknown Source)


```

I had no choice, I had to (slightly) refactor my code in order to implement WebsocketListener instead to overcome this.

**Comment by Gillingham** [comment] 2018-03-07 15:59
Verify your obfuscator isn't removing or changing the decorator. If the jar works before you change it, the problem is in your obfuscator.

**Comment by neilyoung** [comment] 2018-03-07 17:29
Hehe, I can't even remember to have had this kind of problem. Too long ago :) Thanks anyway

**Comment by Gillingham** [comment] 2018-03-07 18:26
You should probably close it then

**Closed** 2018-03-07 18:26 UTC
