### ISSUE TITLE
Multiple instances of Spark

### ISSUE THREAD

**Issue by davidblancke** [perwendel/spark#419] opened 2015-12-11 11:24 UTC
Is it possible to run multiple instances of Spark inside an application?

Would it be as simple as instantiating 2 instances of SparkInstance if this were publically visible?

**Comment by twhitbeck** [comment] 2015-12-18 17:37
While it may not be *quite* as quick-start friendly, I think it'd be a better approach to get rid of the singleton instance and have the user manage instance(s).

**Comment by jakaarl** [comment] 2016-01-07 14:22
Well how about having best of both worlds? Internally, `Spark` uses a singleton `SparkInstance`. Should `SparkInstance` be made public, users would have the choice of using static methods and a singleton instance provided by `Spark`, or instantiate a `SparkInstance` and use that. Naturally, we'd have to ensure that the instances don't share stuff - for example, singletons such as the route matcher provided by `RouteMatcherFactory`.

**Comment by imrichardcole** [comment] 2016-01-17 14:05
I'm hitting this issue as I'm trying to write an integration test that brings up a number of services (each using spark).  They work fine when launched in isolation, but cause errors when they come up in the same process.  Wondering if some classloader magic might work?

**Comment by bjornblomqvist** [comment] 2016-03-11 18:23
@imrichardcole I have done just the thing with classloaders. Two different spark projects, each in a fatjar that i loaded in its own classloader and started with reflection.

**Comment by JWGmeligMeyling** [comment] 2016-03-31 19:27
Duplicate of #281 I believe

**Comment by tipsy** [comment] 2016-03-31 20:57
Was implemented in #499

**Closed by tipsy** 2016-03-31 20:57 UTC
