### ISSUE TITLE
Calling stop() causes java.lang.InterruptedException

### ISSUE THREAD

**Issue by reynders** [perwendel/spark#563] opened 2016-05-19 17:33 UTC
On OSX El Capitan using SparkJava 2.5 expanding on the sparkjava.com hello world example:

    import static spark.Spark.*;

    public class SparkTest {
        public static void main(String[] args) {
            get("/hello", (req, res) -> "Hello World");

            get("/stop", (req, res) -> {
                stop(); 
                return "doh";
            }); 
        }
    }

using browser to hit first hello -> Hello World, then stop -> 15 seconds of silence and then the server throws this up:

20:27:26.448 [qtp276637015-15] ERROR spark.embeddedserver.jetty.EmbeddedJettyServer - stop failed
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method) ~[?:1.8.0_65]
	at java.lang.Thread.join(Thread.java:1253) ~[?:1.8.0_65]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.doStop(QueuedThreadPool.java:161) ~[spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89) ~[spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.stop(ContainerLifeCycle.java:143) ~[spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStop(ContainerLifeCycle.java:161) ~[spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStop(AbstractHandler.java:73) ~[spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.server.Server.doStop(Server.java:476) ~[spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89) ~[spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at spark.embeddedserver.jetty.EmbeddedJettyServer.extinguish(EmbeddedJettyServer.java:145) ~[spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at spark.Service.stop(Service.java:309) ~[spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at spark.Spark.stop(Spark.java:1004) ~[spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at jwnr.SparkTest.lambda$main$1(SparkTest.java:10) ~[spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at spark.RouteImpl$1.handle(RouteImpl.java:61) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at spark.http.matching.Routes.execute(Routes.java:61) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:517) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572) [spark-test-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]

**Comment by reynders** [comment] 2016-05-20 05:54
I don't know if you can call this a fix but this seems to work:

        get("/stop_fix", (req,res) -> {
            new Thread(() -> stop()).start();
            return "yeah";
        });

Anyway the documentation should be updated with the proper intended way of stopping a spark server

**Comment by ruurd** [comment] 2016-05-21 18:35
Oh goody! I'm going to GET /stop or /stop-fix on all your services and your stuff is all dead. Besides: you forgot to implement start so how am I going to start it again?

Serious: this is not how you stop a microservice. In fact, you do not ever stop it. Unless it is from the command line or through a properly secured admin console.

**Comment by reynders** [comment] 2016-05-21 18:49
Firstly: it is usually a good idea to do a graceful shutdown instead of just killing a process so there must be a way to tell the service to do so. Obvious candidates are a java signal handler - and properly secured REST call. In out case the need to start and stop the service is during automated tests so the factual stop part of the API won't have to be part of the production server. So to me it is not waste to mention in the documentation that stop() is not to be called inside a route handler thread

**Comment by ruurd** [comment] 2016-05-21 19:30
Pass the spark process a SIGHUP (that is - the equivalent of Ctrl-C when not running in the background). Jetty handles that and shuts down gracefully. Properly secured REST calls? You mean obvious targets to crack? Keep this stuff out of the REST interface. Keep it even from being handled in the thread that services requests. Doing so is an accident waiting to happen.
That said: why on earth are you calling the deprecated method stop() on the thread that handles your request? You're basically killing yourself and then say hey that's odd I'm dead! 
And yes your fix is not a fix. You're just calling stop on a different thread.

**Comment by AzureusNation** [comment] 2016-07-09 19:50
Ok, done a little research and you cannot shutdown/stop the jetty server from a servlet a.k.a your get method.

I've got a fix for this and will send a pull request shortly.

**Comment by ruurd** [comment] 2016-07-09 19:54
NO DO NOT DO THAT. I really would advise against that. If you do you're opening a huge hole for DDOS attacks. If you want to add it to your own application be my guest but PLEASE PLEASE pretty please do not build that into Spark.

**Comment by AzureusNation** [comment] 2016-07-09 20:00
@ruurd How till this be opening a huge hole for ddos attacks? if a ddos attack was going to be done it could happen already... I don't see what the problem is here. We're trying to find a solution to stop the server if needed. So if we're stopping the server again how is this goig to create a huge hole for dos/ddos attacks?

**Comment by ruurd** [comment] 2016-07-09 20:02
OH

**Closed** 2016-08-31 16:56 UTC
