### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by victorwss** [perwendel/spark#930] opened 2017-10-24 19:05 UTC
Everyone working with Spark already faced an annoying problem: People frequently confuses our Spark with Apache Spark and this might lead to some trouble in explaining to other people that the thing they're googling up is not what we're talking about.

Further, googling up simply for "spark" will give a lot of unrelated results.

To try to disambiguate against Apache Spark when talking to other people, I frequently refer to Spark as "sparkjava" (that is the name of the site). However Apache Spark is frequently used with Java, so this disambiguation is very far from perfect. Also, now that Spark also works with Kotlin, calling it "sparkjava" became a misleading misnomer.

Personally, for me, today was the third time that I had trouble explaining other people what Spark is and why it has nothing to do with Apache Spark. Today, a collaborator couldn't understand what my project had to do with big data (it has nothing to do at all, he was looking to Apache Spark) and he were thinking about things that would be way more expensive in terms of money in my project, risking to have its vetoed or very overbilled due to all that big data stuff. This lead me into a stressful situation in order to explain things to clear out all that confusion.

I really like the name spark, but we must face the truth: Apache Spark is a bigger fish who holds that name and even without them, the name "spark" is already something very likely to be polluted in google results. Spark's name is in fact hindering its very dissemination, adoption and growth, so I propose that we should change its name.

I won't propose a specific name here yet because I have none and my purpose is to just raise the issue by now.

**Comment by hrzafer** [comment] 2017-10-24 19:13
Sparkle ?

**Comment by Matyeu** [comment] 2017-10-25 07:38
Sparky

**Comment by jakaarl** [comment] 2017-10-25 07:43
Spoke? (https://www.thefreedictionary.com/spoke)

**Comment by jakaarl** [comment] 2017-10-25 07:44
In other news, this is a duplicate of #299 which has been closed.

**Comment by tweenietomatoes** [comment] 2017-10-26 17:54
Sparkling Water or Harun Reşit Zafer Framework is better.

**Comment by hrzafer** [comment] 2017-10-26 19:58
@tweenietomatoes, it was just a suggestion. I really care about this framework and as far as I can see name conflict with Apache Spark is a huge problem in terms of branding. If the name was something else this framework would probably be twice as popular as it is now. By the way, I really like the name `spark` and just tried to come up with something not too distant.

**Comment by codemon2002** [comment] 2017-10-26 20:29
I would have to agree this, I believe also people feel like the technology is lesser because it is tiny and simple.  I think a more proud and powerful name might help it gain traction, I like Flare or Flame.

**Comment by victorwss** [comment] 2017-11-02 15:16
@codemon2002 There is a tool called Flare for Apache Spark, so no. For Flame, the is [**this**](http://www.brendangregg.com/blog/2014-06-12/java-flame-graphs.html). Also, those names don't solve the issue that they are likely to be dissolved into many unrelated things in google results.

Since our logo seems to be a multi-tailed comet, maybe this is what we could use for inspiration for another name?

**Comment by eborgbjerg** [comment] 2017-11-28 05:51
Unfortunately, WebSpark is occupied...:(

**Comment by lmalmen** [comment] 2017-12-02 13:21
Framework McFrameworkface

**Comment by thuglnx** [comment] 2018-05-10 10:25
How about “Fast”?

**Comment by tipsy** [comment] 2018-05-10 10:48
We're considering a new name, but it's pending some other things.

**Comment by dessalines** [comment] 2018-05-10 17:34
oooh lets have a little [poll for it](https://simplevote.tk/#/poll/Wxn) . I vote sparkle.

**Comment by hrzafer** [comment] 2018-05-10 17:41
@dessalines Good idea actually. But probably the main contributors have already some options in mind. In addition to that,  do you think the voting system could be simpler?

**Comment by victorwss** [comment] 2018-05-10 17:48
@dessalines Didn't like any of the options.

Sparkle will collide with [this](https://github.com/tweag/sparkle), a project related to Apache Spark, so this would just increase the confusion and not fix anything at all.
Spork will collide with [this](https://github.com/ByteWelder/Spork).
Sparky will collide with [this](https://github.com/kylekyle/sparky).

At least, I didn't found anything that collides to Spoke. But I really dislike that name.

**Comment by tipsy** [comment] 2018-05-10 17:52
Per already has a very unique name in mind, but it depends on some other things. Either he renames it later this year or it won't happen. Either way this issue won't affect his decision, so I will close it now.

**Closed by tipsy** 2018-05-10 17:52 UTC

**Comment by dessalines** [comment] 2018-05-10 22:13
You can click the add more options button, and anyone can add options, but its moot anyway.

**Comment by victorwss** [comment] 2019-01-09 18:30
@tipsy Considering that Spark development is cold and that you are actively mantaining Javalin, maybe there is no need to rename the project at all because Javalin is somewhat already a renamed new version of Spark. I just regret for not being told that before.

**Comment by tipsy** [comment] 2019-01-09 22:33
> @tipsy Considering that Spark development is cold and that you are actively mantaining Javalin, maybe there is no need to rename the project at all because Javalin is somewhat already a renamed new version of Spark. I just regret for not being told that before.

Javalin isn't just a fork/rename, it's a separate project. Most Spark apps are probably easy to port to Javalin, but apps that have custom Jetty config will be a bit different.
