### ISSUE TITLE
How to create subroute?

### ISSUE THREAD

**Issue by GRIM2D** [perwendel/spark#533] opened 2016-04-29 06:15 UTC
Like in Expressjs, how can I create sub routes?

I'd like to use something like:
```java

class APIv1Controller implements SubRoute {
    void prepareRoutes() {
        get("/hello", (req, res) -> "API v1 hello world");
    }
}

use("/api/v1", new APIv1Controller());
```

`http://localhost:8080/api/v1/hello` will return `API v1 hello world`

**Comment by tipsy** [comment] 2016-05-04 20:03
Duplicate of #363

**Closed by tipsy** 2016-05-04 20:03 UTC
Labels: Discussion
