### ISSUE TITLE
Trouble with index.html (welcome file), Spark 2.5

### ISSUE THREAD

**Issue by LaercioMetzner** [perwendel/spark#550] opened 2016-05-10 02:24 UTC
I'm developing an app that's hosted on an Openshift DIY cartige. The front-end is AngularJs and the back-end is pure sparkjava(since version 2.2). After I upgraded spark to version 2.5, I'm unable to access my app like [this](http://jfood-laerciometzner.rhcloud.com/) (http://jfood-laerciometzner.rhcloud.com/) without the index.html at the end of the URL. When informing index.html at the end, like [this](http://jfood-laerciometzner.rhcloud.com/index.html) (http://jfood-laerciometzner.rhcloud.com/index.html), it behaves properly. Here is the snipped I tweaked, any help would be appreciated.

`IS_RUNNING_ON_DIY = System.getenv("OPENSHIFT_DIY_IP") != null;`
`...`
`if (IS_RUNNING_ON_DIY) {`
`//staticFileLocation(STATIC_FILES_LOCATION_PROD);`
`staticFiles.location(STATIC_FILES_LOCATION_PROD);`
`staticFiles.expireTime(1200); // 20 minutes`
`} else {`
`//externalStaticFileLocation(STATIC_FILES_LOCATION_DEV);`
`staticFiles.externalLocation(STATIC_FILES_LOCATION_DEV);`
`}`
`// eighter with or without the below it doesn't behave as expected`
`redirect.get("", "/");`
`redirect.get("/", "/index.html");`

**Comment by tipsy** [comment] 2016-05-10 07:23
I'm guessing you're experiencing the problem described in #548 ?
Could you try doing a build of that branch, and reporting back?

```
git checkout -b MouettE-SC-FIX-547 master
git pull https://github.com/MouettE-SC/spark.git FIX-547
```

**Comment by tipsy** [comment] 2016-05-10 17:30
Well fix this soon @LaercioMetzner, you try this workaround in the meantime:

```get("/", (q, a) -> IOUtils.toString(Spark.class.getResourceAsStream("/public/index.html")));```

You need this import: ```import spark.utils.IOUtils;```

**Comment by MouettE-SC** [comment] 2016-05-10 17:42
Could you give us more details about your setup :
* Openshift does not support java 8 through official cartridges, so I suppose you built your own ?
* Are you using the embedded jetty server ?

**Comment by LaercioMetzner** [comment] 2016-05-10 19:06
@tipsy , I'll try your solution as soon as I get home.

@MouettE-SC , I use a DIY cartrige in which I installed JRE8. I did this way Because at the time of my project's creation Openshift didn't have a pure JSE cartridge, but only JEE. And yes, I run my app as a standalone jar which uses the jetty server provided by Spark.

**Comment by MouettE-SC** [comment] 2016-05-10 20:19
For a mysterious reason your server sends the index file with a content-type of text-plain . I don't think the FIX-547 branch will solve the issue.

I'm trying to reproduce on a simple project but no luck so far. Can you provide more details about the spark setup you use (relevant Spark.* calls in your code) ?

**Comment by LaercioMetzner** [comment] 2016-05-10 21:41
Maybe I should use `staticFiles.header("content-type", "text/html");`. I'll try every of your tips and share the results as soon as I can.

**Comment by tipsy** [comment] 2016-05-10 21:46
> For a mysterious reason your server sends the index file with a content-type of text-plain

We don't set a mime-type currently, see #545.

**Comment by LaercioMetzner** [comment] 2016-05-11 03:18
I tried building my project with an eclipse project dependency to the source at `git pull https://github.com/MouettE-SC/spark.git FIX-547` but I was unable to build my project due to duplicate entries (I do have removed the maven dependency to sparjava).

I tried using a route like `get("/", (req, res) -> IOUtils.toString(Spark.class.getResourceAsStream(STATIC_FILES_LOCATION_PROD + "/index.html")));` but it never gets called unless I comment the call to `staticFiles.location(STATIC_FILES_LOCATION_PROD);`.

If I comment the call to `staticFiles.location(STATIC_FILES_LOCATION_PROD);` and use the route above mentioned, it does return the index body, but any request made by the page (css, js, partial-html) fail.

I tried using `staticFiles.header("content-type", "text/html");`, so that the index.html was properly returned, but it had affected the content-type of all css and js files, which ruined the functionality and layout of the page

**Comment by MouettE-SC** [comment] 2016-05-11 03:28
The fact is that somewhere in the application the content-type is set to text/plain when serving the index.html file from the http GET / request. We need to find where it's done to properly address it.

**Comment by LaercioMetzner** [comment] 2016-05-12 01:44
**My recent tests:**

- With Spark 2.3 my app is able to serve static files flawlessly

- With Spark 2.4 my app is able to serve static files only if index.html is typed at the end of the URL. If it isn't, it returns http 404.

- With Spark 2.5 again my app is able to serve static files only if index.html is typed at the end of the URL. But in this case, if I don't provide index.html at the end of the URL, my app returns the html content of index.html file as plain text.

**The way I deploy my app**

For my source code management and deploy strategy I use two repositories. The first repository I use to keep version history of my source code. The second one I use to deploy the built jar to Openshift. In order to deploy my app, I first build a runnable jar in Eclipse by right clicking my project, selecting Export->Java->Runnable Jar File. Then I put this jar in the diy directory of the repository provided by Openshift. Then I push this repository and the new jar is deployed.

**Sample**

For a better understanding of what I'm doing, I published a seed app that has the same configuration as the app I we've been  talking about up to now.

[This repository](https://github.com/LaercioMetzner/workspace-spark-java-app-source) is the seed of my app. This app is packaged to a runnable jar every single deploy.

[This repository](https://github.com/LaercioMetzner/workspace-spark-java-app) shows the tweaks I made in the default Openshift's diy app repository in order to deploy compiled jars.

**Comment by LaercioMetzner** [comment] 2016-05-16 11:19
Example of people who's having similar issues:

**Comment by MouettE-SC** [comment] 2016-05-18 13:22
After a few tests I think I understand what happened : With spark <= 2.3 the Content-Type header is returned by either spark or jetty whereas on >= 2.4 there is no Content-Type header included ; the problem is that whatever reverse-proxy openshift is using automatically adds a Content-Type header to the answer if it's missing ; This is typically what happens (tested with a very simple test http server) :+1: 

traffic seen by the custom app :
```
<- GET / HTTP/1.1
<- Host: diy-clec.rhcloud.com
<- Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
<- Upgrade-Insecure-Requests: 1
<- User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
<- Accept-Encoding: gzip, deflate, sdch
<- Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
<- Via: 1.1 ubuntu (squid/3.5.12)
<- X-Forwarded-For: 172.19.44.48, 207.236.250.131
<- Cache-Control: max-age=0
<- X-Forwarded-Proto: http
<- X-Forwarded-Port: 80
<- X-Request-Start: t=1463577509596763
<- X-Client-IP: 207.236.250.131
<- X-Forwarded-Host: diy-clec.rhcloud.com
<- X-Forwarded-Server: diy-clec.rhcloud.com
<- Connection: Keep-Alive
<-
-> HTTP/1.0 200 OK
-> Date: Wed, 18 May 2016 09:18:29 -0400
-> Content-Length: 54
-> Server: Java/custom
->
-> <html><head></head><body>Hello Openshift</body></html>
```
Headers received by Chrome :
```Connection:keep-alive
Content-Length: 54
Content-Type: text/plain
Date: Wed, 18 May 2016 09:18:29 GMT
Server: Java/custom
Via: 1.1 ubuntu (squid/3.5.12)
X-Cache: MISS from ubuntu
X-Cache-Lookup: MISS from ubuntu:8888
```

**Comment by MouettE-SC** [comment] 2016-05-18 13:35
Apparently the content-type is guessed by the openshift proxy by the url requested : it sees index.html -> html content type whereas no extension -> text/plain. Setting the content type inside the app seems necessary.

The best thing to do I think is keeping to 2.3 until the MIME-type PR #551 (or an equivalent) is merged into a released version.

**Comment by LaercioMetzner** [comment] 2016-05-18 17:15
@MouettE-SC, I accessed your app at http://diy-clec.rhcloud.com/ , it behaves the same as mine. Thanks for the effort of reproducing my scenario. I'll keep following PR #551 thread.

**Comment by MouettE-SC** [comment] 2016-05-18 18:33
The current app deployed will always have the same answer regardless of the request, so you can try different request and see the resulting content type :

- `/` : text/plain
- `/index.html` : text/html
- `/favicon.ico` : image/vnd.microsoft.icon
- `/public` : text/plain
- `/data.svg` : image/svg+xml

etc.

**Comment by LaercioMetzner** [comment] 2016-11-08 01:47
Hi, recently I noticed the release of spark  2.5 then I tried it (I was running my app on 2.3  up to now), but still the same, index.html is served as plain text when running on Openshift. But this time I spent some more time with the issue and guess, I found something that worked! I was beliving that I wasn't able to declare a get route from root because i was using static files. But the actual reason I wasn't able to do so, was the fact that there was a file called index.html. Yes, now my website does not contain an index.html file anymore (maybe it's the of the World, rs). My landing page has the name of the app (cheff.casa.html) and as a result, I'm now able to intercept a request to root and redirect to wherever I want, like the following
```
get("/", (req, res) -> {
	res.redirect("/cheff.casa.html");
	return null;
});
```
This is my page: http://www.cheff.casa
It's curious that after a server redirection the content-type is made right.
I think this can help people with similar problems.
Thanks!

**Comment by svuksic** [comment] 2016-11-15 10:20
Hi, I have same problem. With Spark version 2.3 I could make runnable jar and with http://localhost:4567 url view index.html from static root directory.
With version 2.5.2 I get index.html for downloading not showing.

 Does anyone have a solution?

**Comment by LaercioMetzner** [comment] 2016-11-15 12:51
I commented the solution that worked for me in my last comment (prior to yours). Have you tried it?

**Comment by svuksic** [comment] 2016-11-15 21:52
Hi @LaercioMetzner, thank you but your solution doesn't work for me because I need "plain" url without page name at the end. 
For example when input http://myURL.com I want to see Index.html page, url http://myURL.com/index.html is not ok for me.

I temporary solved the problem by unpacking jar. When application is not packaged in jar everything works fine but when apliacation is packaged in "fat" jar I can't access to index.html without specified it in URL.

**Closed** 2017-03-02 20:59 UTC
Labels: Bug, Please prioritize
